### ISSUE TITLE
About precompile FLOWExaFMM before using FLOWVPM

### ISSUE THREAD

**Issue by Dhruvin108** [byuflowlab/FLOWVPM.jl#3]
When I try to precompile FLOWExaFMM, something wrong like this:

[ Info: Precompiling FLOWExaFMM [a07d1f4e-0e34-4d8b-bfef-e5b961477d34]
ERROR: LoadError: could not load library "C:\Users\G.julia\packages\FLOWExaFMM\SwcNX\src\fmm"
The specified module could not be found.

What should I do next?
Thank you so much!

**Comment by EdoAlvarezR** [comment]
Hi! Please follow the [installation instructions of FLOWUnsteady](https://flow.byu.edu/FLOWUnsteady/installation/general/) to get FLOWVPM working.
